name             'web_nginx'
maintainer       'vitali_shulhach'
maintainer_email 'vitali_shulhach@epam.com'
description      'nginx installation'
version          '1.0.0'
#depends 'exit_task'
#depends 'jenkins_task'
#depends 'tomcat'
