# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "chef3" do |chef3|
    chef3.vm.box = "ubuntu/trusty64"
    chef3.vm.hostname = "chef3server"
    chef3.vm.network "private_network", ip: "192.168.33.130"
    chef3.vm.provider "virtualbox" do |cfg|
      cfg.name = "chef3-cfg"
      cfg.cpus = 1
      cfg.memory = 4096
   end
    chef3.vm.provision "shell", path: "chef3server.script.sh" 
  end
config.vm.define "chefcl1" do |chefcl1|
    chefcl1.vm.box = "centos/6"
    chefcl1.vm.hostname = "chefcl1"
    chefcl1.vm.network "private_network", ip: "192.168.33.134"
    chefcl1.vm.provider "virtualbox" do |cfg|
      cfg.name = "chefcl1-cfg"
      cfg.cpus = 1
      cfg.memory = 2048
   end
    chefcl1.vm.provision "shell", path: "chef3client.script.sh" 
  end
config.vm.define "chefcl2" do |chefcl2|
    chefcl2.vm.box = "centos/6"
    chefcl2.vm.hostname = "JBOSSNODE"
    chefcl2.vm.network "private_network", ip: "192.168.33.135"
    chefcl2.vm.provider "virtualbox" do |cfg|
      cfg.name = "chefcl2-cfg"
      cfg.cpus = 1
      cfg.memory = 2048
   end
    chefcl2.vm.provision "shell", path: "chef3client.script.sh" 
  end
end


